import time
import json
import urllib.request

BASE_URL = "http://127.0.0.1:8000"

def post(endpoint, data):
    req = urllib.request.Request(
        f"{BASE_URL}{endpoint}",
        data=json.dumps(data).encode('utf-8'),
        headers={'Content-Type': 'application/json'},
        method='POST'
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode('utf-8'))

def get_session_output(sid):
    with urllib.request.urlopen(f"{BASE_URL}/sessions/{sid}/output") as resp:
        return json.loads(resp.read().decode('utf-8'))['output']

def main():
    print("--- Interactive Python Input Test ---")
    
    # 1. Create Session
    sess = post("/sessions", {"name": "interactive-demo", "cols": 80, "rows": 24})
    sid = sess['id']
    print(f"Session ID: {sid}")
    time.sleep(1)

    # 2. Start a Python process that waits for input
    print("\n[Client] Starting Python script that asks for name...")
    # launching python via the terminal
    # Use single quotes for the outer shell command to avoid ! expansion issues in bash
    post(f"/sessions/{sid}/command", {"command": "python3 -c 'name = input(\"Enter your name: \"); print(f\"Nice to meet you, {name}.\")'"})
    
    # Wait a bit for the prompt to appear
    time.sleep(1) 
    
    # Check output to see the prompt
    out = get_session_output(sid)
    print(f"[Terminal Output]: {repr(out)}")
    
    # 3. Send Input (The Name)
    print("\n[Client] Sending name 'Addy'...")
    # The /command endpoint returns the output generated by the command
    res = post(f"/sessions/{sid}/command", {"command": "Addy"})
    out = res['output']
    
    print(f"[Terminal Output]: {repr(out)}")
    
    if "Nice to meet you, Addy." in out:
        print("\n✅ SUCCESS: Input was received and processed!")
    else:
        print("\n❌ FAILURE: Response not found.")

if __name__ == "__main__":
    main()
